Integration Tests - Nested Commenting Feature
wso2/product-apim pull request #10106
Opened 2021-03-03 15:11 UTC by thisaltennakoon

2021-03-05 05:23 UTC, tmkasun approved these changes

2021-03-05 05:23 UTC, tmkasun commented
Let's wait till the github actions complete and merge

2021-03-12 05:21 UTC, tmkasun commented
@thisaltennakoon can you please address the conflicts and give an update here?

2021-03-12 08:47 UTC, thisaltennakoon commented
Conflicts have been resolved @tmkasun

2021-03-12 15:21 UTC, tharindu1st requested changes

2021-03-12 15:21 UTC, tharindu1st commented on config/bam.xml
> -<BamConfig>
why this files are deleted

2021-03-12 15:22 UTC, tharindu1st commented
@thisaltennakoon  pr need to be revisit since pr was removing files

2021-03-18 15:08 UTC, closed without merging

2021-03-18 15:09 UTC, thisaltennakoon commented
The same things are included in this [PR](https://github.com/wso2/product-apim/pull/10259) and it has been merged.