Fixes error starting gateway-worker, traffic-manager profile due to Captcha filter
wso2/product-apim pull request #12087
Opened 2021-11-30 16:24 UTC by Chamindu36

### Purpose 
Fixes https://github.com/wso2/product-apim/issues/12085 for Master

2021-12-01 03:11 UTC, dushaniw commented on modules/distribution/product/src/main/resources/conf/templates/repository/conf/tomcat/carbon/WEB-INF/tm.web.xml.j2
> +    <filter-name>CaptchaFilter</filter-name>
dont we need to remove this captcha filter?

2021-12-01 03:35 UTC, rmsamitha requested changes
Isn't it better to use the same naming convention we have used for axis2.xml and registry.xml?
i.e. web_TM.xml.j2

2021-12-01 06:29 UTC, dushaniw approved these changes

2021-12-01 14:33 UTC, tharindu1st approved these changes

2021-12-02 05:56 UTC, rmsamitha approved these changes

2021-12-02 05:58 UTC, merged