Added test case to validate both basic auth and auth2 enable api through basic auth.
wso2/product-apim pull request #13179
Opened 2023-03-10 09:13 UTC by prasa7

2023-03-10 09:19 UTC, rmsamitha commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/APISecurityTestCase.java
> +       e         "Basic " + Base64.encodeBase64String(user1.concat("@").concat(this.user.getUserDomain()).concat(":")
typo

2023-03-10 09:24 UTC, rmsamitha commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/APISecurityTestCase.java
> +    private final String basicAuthSecuredAPIContext = "BasicAuthAndOauth2SecuredAPI";
Duplicate variables

2023-03-10 09:29 UTC, rmsamitha requested changes

2023-03-10 09:29 UTC, rmsamitha commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/APISecurityTestCase.java
> +            "testInvokeBasicAuthAfterCredentialsInvalid"})
Fix the test description

2023-03-10 09:29 UTC, rmsamitha commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/APISecurityTestCase.java
> +    public void testInvocationWithBasicAuthandOauth2ForAPIKey() throws Exception {
Test method name not conveying what is tested

2023-03-10 09:29 UTC, rmsamitha commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/APISecurityTestCase.java
> +        requestHeaders.put("Authorization", "Basic abcce");
Header value should be set correctly

2023-03-13 18:41 UTC, prasa7 commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/APISecurityTestCase.java
> +       e         "Basic " + Base64.encodeBase64String(user1.concat("@").concat(this.user.getUserDomain()).concat(":")
done

2025-06-19 15:32 UTC, tgtshanika commented
Closing due to inactivity

2025-06-19 15:32 UTC, closed without merging