Fix test failures due to REST API validation
wso2/product-apim pull request #9373
Opened 2020-10-19 01:52 UTC by vithu30

Fix test failures due to changes introduced in the PR -https://github.com/wso2/carbon-apimgt/pull/9313, to validate the request parameters in REST API level

2020-10-19 02:04 UTC, malinthaprasan approved these changes

2020-11-01 09:05 UTC, tharindu1st requested changes

2020-11-01 09:05 UTC, tharindu1st commented on modules/integration/tests-integration/tests-backend/src/test/resources/oas/v2/apiData.json
> -  "createdTime": "2019-09-17 17:49:55.251",
shall we remove createdTime and lastUpdatedTime. since this was not updated from rest API level.

2020-11-04 05:06 UTC, tharindu1st approved these changes

2020-11-04 05:31 UTC, merged